# Config for natejohnston.info public site and blog
# vim: nospell
baseURL: https://natejohnston.info
title: Nate Johnston
theme: hugo-theme-stack
languageCode: en-us
themesdir: /sync/web/themes

params:
    mainSections:
        - post
    featuredImageField: image
    rssFullContent: true

related:
    includeNewer: true
    threshold: 60
    toLower: false
    indices:
        - name: tags
          weight: 100

        - name: categories
          weight: 200

markup:
    goldmark:
        renderer:
            ## Set to true if you have HTML content inside Markdown
            unsafe: false
    tableOfContents:
        endLevel: 4
        ordered: true
        startLevel: 2
    highlight:
        noClasses: false
        codeFences: true
        guessSyntax: true
        lineNoStart: 1
        lineNos: true
        lineNumbersInTable: true
        tabWidth: 4
